### PR TITLE
fix/bug-id-41

### PR DESCRIPTION
**Pull request by LukeHeimen**
## Description
This PR will introduce a fix for the issue stated in [Bug Ticket ID 41](https://scibizinformatics.slack.com/lists/T04RT6J7G/F07N8SDNF6V?record_id=Rec07T2HBQAEA), wherein some dialogs/modals can be duplicated when clicking on some buttons multiple times. Some modals also remains in the screen when exiting the page where they were generated.

Acceptance criteria should be when opening modals, they can only be opened once. They can be opened again after closing said modal.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)

## Test Notes
The fix was tested locally on a desktop and mobile device. The fix was applied in modals of the following pages and components:
- (Home Page) BCH price chart modal
- (Home Page) add new fungible token modal
- (Home Page) delete token modal
- (Home Page) scan for tokens/unlisted assets modal
- (Send Page) set max modal
- (Collectibles) NFT dialog
- (Crypto Swap) token selection modal
- AnyHedge modals
- Merchant Admin modals
- Wallet Connect modals

## @mentions
@nikkadejesus for testing

### CODE REVIEW

**Comment by nikkadejesus** [comment]
I just found another issue in [ignored tokens list](https://drive.google.com/file/d/1vGQDutCvSTptfomi8FN1me0LBNj_FHkO/view?usp=drive_link). Can you please verify @LukeHeimen . Everything else is good to go.

**Comment by LukeHeimen** [comment]
> I just found another issue in [ignored tokens list](https://drive.google.com/file/d/1vGQDutCvSTptfomi8FN1me0LBNj_FHkO/view?usp=drive_link). Can you please verify @LukeHeimen . Everything else is good to go.

@nikkadejesus I just pushed a fix for this one. Thanks for catching what I missed.

**Comment by nikkadejesus** [comment]
> > I just found another issue in [ignored tokens list](https://drive.google.com/file/d/1vGQDutCvSTptfomi8FN1me0LBNj_FHkO/view?usp=drive_link). Can you please verify @LukeHeimen . Everything else is good to go.
> 
> @nikkadejesus I just pushed a fix for this one. Thanks for catching what I missed.

@LukeHeimen I am still able to replicate the issue. Can you please verify?

**Comment by nikkadejesus** [comment]
> > I just found another issue in [ignored tokens list](https://drive.google.com/file/d/1vGQDutCvSTptfomi8FN1me0LBNj_FHkO/view?usp=drive_link). Can you please verify @LukeHeimen . Everything else is good to go.
> 
> @nikkadejesus I just pushed a fix for this one. Thanks for catching what I missed.

@LukeHeimen I am still able to replicate the issue. Can you please verify?

**Pull request merged**
