### PR TITLE
fix/bug-id-48

### PR DESCRIPTION
**Pull request by LukeHeimen**
## Description
This PR includes a fix for the issue stated in the [Bug Ticket ID 48](https://scibizinformatics.slack.com/lists/T04RT6J7G/F07N8SDNF6V?record_id=Rec07V7P0BWV8), wherein the send slider and Add Another Recipient is not showing when adding recipients by uploading QR code.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)

## Test Notes
The fix has been tested both in desktop and mobile devices. Replication of the issue is stated below:
1. Go to the QR page then click on Upload QR and upload a QR code.
2. After redirection to the send page, enter an amount to send.
3. Click on Add Another Recipient button.
4. On the Recipient field, click on Upload to upload another QR code.
5. Enter an amount to send.
6. After entering amount, the send slider and Add Another Recipient button should now appear.

## @mentions
@nikkadejesus for testing

### CODE REVIEW

**Comment by nikkadejesus** [comment]
I've just checked and the send slider and Add Another Recipient are already showing, but only when user has entered the amount in their currency. I have tried entering an amount in BCH but the send slider and Add Another Recipient are not showing. Kindly verify @LukeHeimen

**Comment by LukeHeimen** [comment]
> I've just checked and the send slider and Add Another Recipient are already showing, but only when user has entered the amount in their currency. I have tried entering an amount in BCH but the send slider and Add Another Recipient are not showing. Kindly verify @LukeHeimen

**Comment by LukeHeimen** [comment]
@nikkadejesus The slider and button not appearing after you enter in BCH is the intended outcome, because when you change your set amount to BCH or vise versa, all amounts entered in all recipients are cleared/set to zero.

**Comment by nikkadejesus** [comment]
> @nikkadejesus The slider and button not appearing after you enter in BCH while having multiple recipients is the intended outcome, because when you change your set amount to BCH or vise versa, all amounts entered in all recipients are cleared/set to zero. You have to reenter the amounts again.

I see. Are we considering making an improvement for this? UX-wise, I think it would be a hassle, as a user, to have to re-enter the amounts every time I add a new recipient.

**Comment by joemarct** [comment]
> Are we considering making an improvement for this in the future? UX-wise, I think it would be a hassle, as a user, to have to re-enter the amounts every time I add a new recipient.

Yes, please note this as an improvement.

**Pull request merged**
